In [ ]:
import numpy as np

In [60]:
def QR_with_pivoting(A):
  col_norms_with_indices = np.array([(i, np.linalg.norm(A[:, i])) for i in range(0, A.shape[1])])
  sorted_col_norms_with_indices = sorted(col_norms_with_indices, key=lambda x: x[1], reverse=True)

  permutation = [int(pair[0]) for pair in sorted_col_norms_with_indices]
  P = np.eye(A.shape[1])
  P = P[permutation]

  AP = A @ P
  Q, R = np.linalg.qr(AP)

  return Q, R, P

In [39]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


Q, R, P = QR_with_pivoting(A)

print(Q @ R @ P.transpose())

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [44]:
def max_abs_elem_ind(A):
  max_abs_value = -1
  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        abs_value = abs(A[i, j])
        if abs_value > max_abs_value:
            max_abs_value = abs_value
            max_index = (i, j)
  return max_index

In [123]:
def maxvol(A):
  n = A.shape[0]
  r = A.shape[1]

  Q, R, P = QR_with_pivoting(A)
  A = A @ P[:, :r]


  rev_submatrix = np.linalg.inv(A[:r, :])
  B = A @ rev_submatrix

  i, j = max_abs_elem_ind(A)
  submatrix_indices = np.arange(r)
  while i > r:
    v = B[:, j]
    v[j] -= 1
    v[i] += 1

    q = B[i,:]
    q[j] -= 1

    B = B - np.outer(v, q)/B[i,j]
    i, j = max_abs_elem_ind(A)
    if B[i, j] < 1e-15:
      break
    submatrix_indices[j] = i
    print(B)
    input()

  return submatrix_indices, B, P

In [122]:
n = 5
r = 2

B = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        B[i, j] = np.sin(i + j)

submatrix = B[:,:r]

indices, B_hat, P = maxvol(submatrix)

temp = np.zeros((n, n))
for i in range(r):
  for j in range(r):
    temp[i,j] = P.transpose()[i,j]
for i in range(r, n):
  temp[i, i] = 1

B_approx = B_hat @ B[indices, :] @ temp.transpose()
print(np.linalg.norm(B_approx - B))

[[0. 1.]
 [1. 0.]]
15.27940421955909
